/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  images: {
    domains: [
      'source.unsplash.com',
      'www.gravatar.com',
      'imagedelivery.net',
      'images.clerk.dev',
      'gravatar.com',
      'www.monote.ai',
      'monote.ai',
      'monote-*-darasus-team.vercel.app',
      'localhost',
    ],
  },
  transpilePackages: [
    'api',
    'auth-features',
    'card-features',
    'cards',
    'client-env',
    'config',
    'database',
    'email',
    'error',
    'hooks',
    'inngest-client',
    'lib',
    'server-env',
    'stripe-webhook-input-validation',
    'tokens',
    'types',
    'ui',
    'utils',
  ],
};
