name: ci
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]
jobs:
  e2e:
    # only runs this job on successful deploy
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: wannago-small-4-core-runner
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Print URL 🖨
        run: echo Testing URL ${{ github.event.deployment_status.target_url }}

      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
            fetch-depth: 2  

      - uses: pnpm/action-setup@v2
        with:
            version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'pnpm'
            
      - name: Install dependencies
        run: pnpm install

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
            path: ~/.cache/Cypress
            key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
            restore-keys: |
              cypress-${{ runner.os }}-cypress-

      - name: install dependencies and verify Cypress
        env:
            CI: 1
        run: |
            pnpm install
            pnpm dlx cypress verify
            pnpm dlx cypress info
            pnpm dlx cypress version
            pnpm dlx cypress version --component package
            pnpm dlx cypress version --component binary
            pnpm dlx cypress version --component electron
            pnpm dlx cypress version --component node
        
      - name: Cypress run
        run: pnpm turbo run test:e2e:ci --filter web-e2e
        env:
            CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
            NEXT_PUBLIC_BASE_URL: ${{ github.event.deployment_status.target_url }}
            NEXT_PUBLIC_VERCEL_URL: ${{ github.event.deployment_status.target_url }}
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
            VERCEL_ANALYTICS_ID: ${{ secrets.VERCEL_ANALYTICS_ID }}
            VERCEL_WEB_ANALYTICS_ID: ${{ secrets.VERCEL_WEB_ANALYTICS_ID }}
            VERCEL_ENV: ${{ secrets.VERCEL_ENV }}
            MIGRATE_DATABASE_URL: ${{ secrets.MIGRATE_DATABASE_URL }}
            NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            PRISMA_GENERATE_DATAPROXY: ${{ secrets.PRISMA_GENERATE_DATAPROXY }}
            CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
            QSTASH_URL: ${{ secrets.QSTASH_URL }}
            QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
            QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
            QSTASH_NEXT_SIGNING_KEY: ${{ secrets.QSTASH_NEXT_SIGNING_KEY }}
            NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            NEXT_PUBLIC_VERCEL_ENV: ${{ secrets.NEXT_PUBLIC_VERCEL_ENV }}
            STRIPE_API_SECRET: "STRIPE_API_SECRET"
            STRIPE_ENDPOINT_SECRET: "STRIPE_ENDPOINT_SECRET"
            STABILITY_AI_API_KEY: "STABILITY_AI_API_KEY"
            INNGEST_SIGNING_KEY: ${{ secrets.INNGEST_SIGNING_KEY }}
            INNGEST_EVENT_KEY: ${{ secrets.INNGEST_EVENT_KEY }}

      # if you are NOT using Cypress GitHub Integration App, then set commit status manually
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions
      - name: Cypress tests ✅
        if: ${{ success() }}
        # set the merge commit status check
        # using GitHub REST API
        # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "e2e",
            "state": "success",
            "description": "Cypress tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Cypress tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "e2e",
            "state": "failure",
            "description": "Cypress tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'