name: Sync
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync branches
        run: |
            git config user.name "Ilya Daraseliya"
            git config user.email "idarase@gmail.com"
            git fetch
            git checkout test-automation
            git rebase origin/main
            git push origin test-automation